server:
  port: 8080

# ============================================================
# 运维管理系统配置
# 除了 api-rbac 地址, 业务系统几乎不需要额外配置权限相关的东西
# ============================================================
ops:
  rbac:
    url: http://localhost:8087/api/v1
